name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: "METRICS_TOKEN"
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_topics: yes
          plugin_topics_limit: 30
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
             gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          plugin_stars: yes
          plugin_stars_limit: 5
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_archived: no
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 2
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_only: Awesome
          plugin_calendar: yes
          plugin_calendar_limit: 0
          plugin_achievements: yes
          plugin_achievements_only: >-
              polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
              scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          
